"""Cria tabelas Usuario, PokemonUsuario e TipoPokemon com relacao N para N

Revision ID: 9a4304a29cc7
Revises: 
Create Date: 2025-09-30 23:52:27.196725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a4304a29cc7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tipo_pokemon',
    sa.Column('id_tipo_pokemon', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id_tipo_pokemon'),
    sa.UniqueConstraint('descricao')
    )
    op.create_table('usuario',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('login', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('senha', sa.String(length=200), nullable=False),
    sa.Column('dt_inclusao', sa.DateTime(), nullable=False),
    sa.Column('dt_alteracao', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_usuario'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('login')
    )
    op.create_table('pokemon_usuario',
    sa.Column('id_pokemon_usuario', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('imagem_url', sa.String(length=255), nullable=True),
    sa.Column('favorito', sa.Boolean(), nullable=True),
    sa.Column('grupo_batalha', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_pokemon_usuario')
    )
    op.create_table('pokemon_tipo_associacao',
    sa.Column('pokemon_usuario_id', sa.Integer(), nullable=False),
    sa.Column('tipo_pokemon_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pokemon_usuario_id'], ['pokemon_usuario.id_pokemon_usuario'], ),
    sa.ForeignKeyConstraint(['tipo_pokemon_id'], ['tipo_pokemon.id_tipo_pokemon'], ),
    sa.PrimaryKeyConstraint('pokemon_usuario_id', 'tipo_pokemon_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pokemon_tipo_associacao')
    op.drop_table('pokemon_usuario')
    op.drop_table('usuario')
    op.drop_table('tipo_pokemon')
    # ### end Alembic commands ###
